# tools/compilers/compiler_glyph.py

from __future__ import annotations
from pathlib import Path
from typing import Literal

from tools.loaders.load_mji_00602_xlsx import load_mji_00602_xlsx
from tools.loaders.load_mjih_00201_xlsx import load_mjih_00201_xlsx
from tools.loaders.load_dwpi_mdb import load_dwpi_mdb
from tools.core.model import GlyphRecord


# ------------------------------------------------------------
# glyph name の重複チェック
# ------------------------------------------------------------

def ensure_unique_names(records: list[GlyphRecord]):
    seen = set()
    duplicates = []

    for rec in records:
        if rec.name in seen:
            duplicates.append(rec.name)
        else:
            seen.add(rec.name)

    if duplicates:
        raise ValueError(f"Duplicate glyph names detected: {duplicates}")


# ------------------------------------------------------------
# VERSION と GLYPH_TABLE の書き出し
# ------------------------------------------------------------

def write_glyph_table_py(out_path: Path, descriptions: list[str], version: str, records: list[GlyphRecord], sort: bool = False):
    lines = []

    lines.append("# -*- coding: utf-8 -*-")
    lines.append("# Auto-generated by compiler_glyph.py")
    lines.append("# NOTE: This file contains Japanese characters in comments.")
    lines.append("#       All content is encoded in UTF-8 (without BOM).")
    for desc in descriptions:
        lines.append(f"# {desc}")
    
    lines.append("")
    lines.append(f"VERSION: str = {version!r}")

    lines.append("")
    lines.append("GLYPH_TABLE: dict[str, dict[str, str | bool]] = {")

    # sortが真の場合、name でソート
    for rec in sorted(records, key=lambda r: r.name) if sort else records:
        lines.append(f"    {rec.name!r}: {{")
        lines.append(f"        # {rec.comment}")
        lines.append(f"        'b': {rec.b!r},")
        lines.append(f"        'v': {rec.v!r},")
        lines.append(f"        'active': {rec.active!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


# ------------------------------------------------------------
# 出力先ファイルのフルパス を生成
# ------------------------------------------------------------
def build_dataset_output_path(code_dir: Path, dataset_name: str, version: str) -> Path:
    """
    Build the full output path for the generated glyph table.
    """

    def slugify(s: str) -> str:
        return s.lower().replace(".", "_").replace("-", "_")

    name_part = slugify(dataset_name)
    ver_part = f"v{slugify(version)}"

    base = (
        code_dir
        / "glyph"
        / f"{name_part}_{ver_part}"
        / "src"
        / "tofurengo_data"
        / name_part
        / ver_part
    )

    return base / f"data_{name_part}_{ver_part}.py"


# ------------------------------------------------------------
# GLYPH_TABLE を生成
# ------------------------------------------------------------

def compile_mj_v6_02_201(code_dir: Path, base_from: Literal['jibo', 'onka']):
    """
    MJ（漢字）＋ MJIH（変体仮名）を合成して GLYPH_TABLE を生成
    """

    res_name = "mj"
    res_ver = "6.02.201" if base_from == "jibo" else "6.02.201-onka"
    out_path = build_dataset_output_path(code_dir, res_name, res_ver)

    xlsx_mj = code_dir / "tools/data" / "mji.00602.xlsx"
    xlsx_mjih = code_dir / "tools/data" / "MJIH00201.xlsx"
    
    base_from_name = "字母" if base_from == "jibo" else "音価１"

    descriptions = [
        "",
        f"set: {res_name}",
        "",
        f"file 1: {xlsx_mj.name}",
        f"file 2: {xlsx_mjih.name}",
        f"        ※ 基本字形：{base_from_name}",
        "",
        # --- 出典情報を追加 ---
        "-----------------------------------------------------------------------------",
        "本データは、IPA（独立行政法人 情報処理推進機構）が公開する「MJ文字情報一覧表」および",
        "「MJ文字情報一覧表 変体仮名編」の XLSX ファイルを基に生成されている。",
        "",
        "これらの XLSX ファイルは IPA の著作物であり、次の公式サイトから取得した：",
        "",
        "    https://moji.or.jp/mojikiban/mjlist/",
        "",
        "本データは、当該 XLSX を読み込み、変体仮名を含めたMJ文字情報の統合テーブルとして",
        "Python モジュール形式で再構成したものである。",
        "-----------------------------------------------------------------------------",
    ]
        
    # --- MJ（漢字編） ---
    print(f"[compiler] Loading MJ Kanji: {xlsx_mj}")
    records_mj = load_mji_00602_xlsx(xlsx_mj)
    print(f"[compiler] Loaded MJ Kanji: {len(records_mj)} records")

    # --- MJIH（変体仮名編） ---
    print(f"[compiler] Loading MJ Hentaigana: {xlsx_mjih}")
    records_mjih = load_mjih_00201_xlsx(xlsx_mjih, base_from)
    print(f"[compiler] Loaded MJ Hentaigana: {len(records_mjih)} records")

    # --- 合成（list のまま） ---
    records = records_mj + records_mjih
    print(f"[compiler] Total records (before duplicate check): {len(records)}")

    # --- name の重複チェック ---
    ensure_unique_names(records)
    print("[compiler] Name uniqueness check passed")

    write_glyph_table_py(out_path, descriptions, res_ver, records)
    print(f"[compiler] Wrote: {out_path.resolve()}")


def compile_mj_plus_v4_10(code_dir: Path):
    """
    DWPI明朝4.10版の GLYPH_TABLE を生成（MJ+対応）
    """

    res_name = "mj_plus"
    res_ver = "4.10"
    out_path = build_dataset_output_path(code_dir, res_name, res_ver)

    mdb_path = code_dir / "tools/data" / "deluxe文字選択DWPI明朝4.10版V2.0.mdb"
    
    descriptions = [
        "",
        f"set: {res_name}",
        "",
        f"file: {mdb_path.name}",
        "",
        # --- 出典情報を追加
        "-----------------------------------------------------------------------------",
        "本データは、デジタル広域推進機構 が公開する検索システム「Deluxe文字選択（MJ+対応）」",
        "の mdb ファイルを基に生成されている。",
        "",
        "この mdb ファイルは デジタル広域推進機構 の著作物であり、次の公式サイトから取得した:",
        "",
        "    https://www.digitalwidearea.org/dwpi_mincho",
        "",
        "本データは、当該 mdb を読み込み、行政事務標準文字に対応したテーブル（MJ+対応）として",
        "Python モジュール形式で再構成したものである。",
        "-----------------------------------------------------------------------------",

    ]


    print("Absolute path:", mdb_path)
    records = load_dwpi_mdb(mdb_path)
    print("Total records:", len(records))
    
    # --- name の重複チェック ---
    ensure_unique_names(records)
    print("[compiler] Name uniqueness check passed")

    write_glyph_table_py(out_path, descriptions, res_ver, records)
    print(f"[compiler] Wrote: {out_path.resolve()}")

def compile_mj_plusx_v1_20(code_dir: Path):
    """
    DWPIex明朝1.2版の GLYPH_TABLE を生成（MJ+対応）
    """

    res_name = "mj_plusx"
    res_ver = "1.20"
    out_path = build_dataset_output_path(code_dir, res_name, res_ver)

    mdb_path = code_dir / "tools/data" / "deluxe文字選択DWPIex明朝1.2版.mdb"
    
    descriptions = [
        "",
        f"set: {res_name}",
        "",
        f"file: {mdb_path.name}",
        "",
        # --- 出典情報を追加
        "-----------------------------------------------------------------------------",
        "本データは、デジタル広域推進機構 が公開する検索システム「Deluxe文字選択（MJ+対応）」",
        "の mdb ファイルを基に生成されている。",
        "",
        "この mdb ファイルは デジタル広域推進機構 の著作物であり、次の公式サイトから取得した:",
        "",
        "    https://www.digitalwidearea.org/dwpi_mincho",
        "",
        "本データは、当該 mdb を読み込み、行政事務標準文字に対応したテーブル（MJ+対応）として",
        "Python モジュール形式で再構成したものである。",
        "-----------------------------------------------------------------------------",

    ]


    print("Absolute path:", mdb_path)
    records = load_dwpi_mdb(mdb_path)
    print("Total records:", len(records))
    
    # --- name の重複チェック ---
    ensure_unique_names(records)
    print("[compiler] Name uniqueness check passed")

    write_glyph_table_py(out_path, descriptions, res_ver, records)
    print(f"[compiler] Wrote: {out_path.resolve()}")


# ------------------------------------------------------------
# main
# ------------------------------------------------------------

def main():
    code_dir = Path(__file__).resolve().parent.parent.parent

    compile_mj_v6_02_201(code_dir, "jibo")
    compile_mj_v6_02_201(code_dir, "onka")
    compile_mj_plus_v4_10(code_dir)
    compile_mj_plusx_v1_20(code_dir)


if __name__ == "__main__":
    main()
