# code/glyph/<project folder>/pyproject.toml
[project]
name = "tofurengo-data-mj-plusx-v1-20"

dynamic = ["version"]
requires-python = ">=3.8"
authors = [{ name = "jp-rad" }]
description = "Unicode UCS/IVS utilities for MJ/GJ glyph processing"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jp-rad/tofurengo"
Repository = "https://github.com/jp-rad/tofurengo"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/tofurengo"]
