# code/glyph/<project folder>/pyproject.toml
[project]
name = "tofurengo-data-mj-v6-02-201-onka"

dynamic = ["version"]
requires-python = ">=3.8"
authors = [{ name = "jp-rad" }]
description = "Unicode UCS/IVS utilities for MJ/GJ glyph processing"
readme = "README.md"
license = { text = "CC-BY-SA-2.1-JP" }
license-files = ["LICEN[CS]E*"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "License :: Other/Proprietary License", # CC BY-SA 2.1 JP lacks a standard PyPI classifier keyword
]

[project.urls]
Homepage = "https://github.com/jp-rad/tofurengo"
Repository = "https://github.com/jp-rad/tofurengo"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/tofurengo_data"]
